### ISSUE TITLE
:art:Design: 프로필 디자인 구현

### ISSUE THREAD

**Issue by nkEllaaa** [Sowith/sowith#18]
## Description
- 프로필 디자인 구현을 위한 이슈입니다

## To-do
- [x] 프로필 단 디자인
- [x] 프로필 페이지 레이아웃
- [x] 프로필 탑 레이아웃
- [x] 프로필 탭 메뉴 레이아웃
- [x] 프로필 바텀 레이아웃
- [x] 프로필 페이지 디자인 구현
- [x] 프로필 탑 디자인 구현
- [x] 프로필 탭 메뉴 디자인 구현
- [x] 프로필 바텀 디자인 구현
- [x] 탭 메뉴 StepBar 컴포넌트로 분리

## 기타 사항
- 없습니다

<br>
