### ISSUE TITLE
🎨Design: 게시물작성 - 폴더모달/유저태그모달 구현 및 수정

### ISSUE THREAD

**Issue by D-Sup** [Sowith/sowith#30]
## Description
- 폴더 생성 모달 디자인 구현과 유저태그모달을 디자인 수정사항에 맞게 수정하기 위한 이슈입니다.
- 이전에 마이그레이션을 완료한 코드에서 일부분 보완을 위해 수정했습니다. 

## To-do
- [x] 누락된 아이콘 추가
- [x] 폴더생성페이지 추가
- [x] 체크박스 컴포넌트 추가
- [x] 이전 마이그레이션 보완 및 수정
- [x] 더미데이터 생성

## 기타 사항
- 누락되었던 아이콘을 추가해서, 현재 main 브랜치에서 폴더 리스트 공통 컴포넌트에 들어가는 `bookmark.svg` 잘못 추가되어있는 것 같아서 내부코드만 수정 했습니다! 컴포넌트 사용하실 떄 참고해주세요!

<br>
