### ISSUE TITLE
:art:Design: 기타 누락된 디자인 구현들

### ISSUE THREAD

**Issue by nkEllaaa** [Sowith/sowith#34]
## Description
- 회원가입과 프로필 단에서 누락되었던 디자인을 구현하기 위한 이슈입니다.

## To-do
- **스플래쉬**
  - [x] 스플래쉬 화면
- **회원가입**
  - [x] 회원가입 완료 후 로그인으로 이동하는 페이지 
  - [x] 회원가입 단에서 모든 데이터가 입력되어야 회원가입 버튼이 활성화되도록 수정
- **그룹UI변경**
  - [x] 이미지 개수 3 -> 삭제
  - [x] 함께하는 친구 삭제, 통일하여 그룹 총 인원으로 수정
  - [x] 게시글 작성 시간 분기처리 ( n초 전, n분 전, n시간 전, n일 전)
  - [x] 이미지 좌측 하단에 즐겨찾기 추가
  - [x] 바텀에 구분선 삭제 
  - [x] 참여한 그룹과 즐겨찾기 한 그룹 사이의 구분 단 추가
- 그룹 디테일
  - [x] arrowButton 삭제  

## 기타 사항
- 더 빠진 부분이 있으면 코멘트 달아주세요

<br>
