### ISSUE TITLE
🛠Feat: 필터페이지 구현 && 게시글 페이지 데이터 상호작용

### ISSUE THREAD

**Issue by D-Sup** [Sowith/sowith#42]
## Description
- 필터페이지 구현 및 게시글 페이지에서의 모달과 인풋 박스와의 데이터 상호작용을 다룬 이슈입니다.

## To-do
- [x] 북마크, 폴더 아이콘 복구
- [x] 폴더박스 찌그러짐 현상 해결
- [x] 해쉬태그, 유저태그 그라데이션 제거
- [x] 모달 컴포넌트 상위 컴포넌트로 이동
- [x] URL 변동없이 상태값으로 리다이렉션 구현
- [x] Searchbar에 들어가는 데이터와 인풋데이터와 상호작용
- [x] 필터 페이지 구현
  - [x] 사진마다 적용된 필터 저장
  - [x] 사진 슬라이드
    - [x] 화면의 좌측/우측 부분을 클릭 시 슬라이드
    - [x] 화면을 좌측/우측으로 스와이프 시 슬라이드
  - [x] 필터 슬라이드
    - [x] 필터를 직접 클릭 시 슬라이드 && 필터 적용
    - [x] 화면을 좌측/우측으로 스와이프 시 슬라이드 && 동적으로 필터 적용
    - [x] 스와이프 이후 스크롤이 멈춘 곳에 근접하는 필터에 자리 교정

## 기타 사항
- 추후 추가 예정입니다.

<br>
