### ISSUE TITLE
🎨Design: 게시글 뷰 디자인 구현

### ISSUE THREAD

**Issue by D-Sup** [Sowith/sowith#43]
## Description
- 게시글 뷰 디자인구현을 다룬 이슈입니다

## To-do
- [x] 게시글 뷰 페이지 구현
- [x] 더보기 버튼 클릭 시 뜨는 모달 구현
- [x] 좋아요 누른 유저와 로그인 유저와 동일할 경우 하트 활성화
- [x] useModalControl 훅 수정 (높이 조절이 가능하도록)
- [x] useAlertControl 훅 수정 (위치 조정이 가능하도록)
- [x] 댓글 모달 구현
  - [x] 인풋 박스 텍스트양에 따라 자동높이 조절
- [x] 알림 모달 추가
- [x] FireStore 연결 - 데이터를 불러와서 화면에 뿌려주기 
- [x] 라우트 추가
- [x] 더보기 버튼이 글이 길 경우만 보이기
- [x] 댓글 창 높이에 따라 동적으로 뷰높이 증가

## 기타 사항
- 추후 추가 예정입니다.
