### ISSUE TITLE
🛠Feat: 게시물 작성 - 데이터 연동 && Atom 추가

### ISSUE THREAD

**Issue by D-Sup** [Sowith/sowith#53]
## Description
- 게시물 작성 페이지 Firestore 데이터 연동과 게시물 정보 관련 Atom 추가를 다룬 이슈입니다.

## To-do
- [x] 모달 훅 리팩토링
- [x] 시간 포맷 훅추가
- [x] 사진 슬라이드 컴포넌트 리팩토링
- [x] 뷰 맨위에 여백주기
- [x] 유저 아이템 클릭 시 순서정렬
- [x] 게시물 저장용 Atom 추가
- [x] 폴더 생성 페이지 뷰 이상으로 이탈 해결
- [x] 정보입력 모달 다시 열 때 데이터 유지

## 기타 사항
- 추후 추가 예정입니다.
