### ISSUE TITLE
🛠Feat: 검색 기능 Firebase 연동

### ISSUE THREAD

**Issue by starcradle101** [Sowith/sowith#65]
## Description
- 본 이슈는 검색 기능과 Firebase를 연동하는 이슈입니다.

## To-do
- [x] SearchAccountList, SearchAccountItem에 대한 Firebase 연동
- [x] SearchFolderList, SearchFolderItem에 대한 Firebase 연동
- [x] SearchPostList, SearchPostItem에 대한 Firebase 연동
- [x] SearchTagList, SearchTagItem에 대한 Firebase 연동
- [x] SearchTrendingFolderList, SearchTrendingFolderPage, SearchTrendingTagList에 대한 Firebase 연동
- [x] useFirestoreUpdate에 Public Field를 업데이트하기 위한 유틸함수 구현
- [x] 숫자 포맷팅을 위한 formatNumber 유틸함수 추가
- [x] SearchHistoryPage 컴포넌트에서 검색 결과 표현 순서 변경

## 기타 사항
- Prettier 컨벤션에 따른 일부 코드 수정

<br>
