### ISSUE TITLE
🎨Design: 게시물 작성 - 레이아웃 마크업 및 스타일

### ISSUE THREAD

**Issue by D-Sup** [Sowith/sowith#7]
## Description
게시물 작성 페이지의 마크업, 스타일을 다루는 이슈

## To-do
- [x] 임시 상태관리 컴포넌트 추가
- [x] 사진 설정 페이지 추가
- [x] 정보 입력 페이지 추가
- [x] 위치 설정 페이지 추가
- [x] 폴더 설정 페이지 추가
- [x] 라우트 추가

## 기타사항
마크업 스타일은 기본적으로 마쳤고, 유저 플로우에 맞게 컴포넌트가 흘러가도록 임시적으로 관리할 수 있는 상위 컴포넌트를 생성했습니다.
