### ISSUE TITLE
🛠Feat: 홈 화면 기능 구현

### ISSUE THREAD

**Issue by starcradle101** [Sowith/sowith#73]
## Description
- 홈 화면의 기능 구현을 진행하는 이슈입니다.

## To-do
- [ ] 검색 바 클릭 시 검색 메인 페이지 이동 기능
- [ ] 현재 위치 버튼 클릭 시 현재 위치로 지도 뷰 이동
- [ ] 게시글 뷰 버튼 클릭 시 게시글 뷰로 이동
- [ ] 하단 게시글 모달 상호작용 기능

## 기타 사항
- 핵심 기능을 위주로 첫 이슈에 작성하고, 이후 세부 기능을 업데이트 할 예정입니다.

<br>
