### ISSUE TITLE
🐞Fix: 카테고리 검색 페이지 라우터 수정

### ISSUE THREAD

**Issue by starcradle101** [Sowith/sowith#75]
## Description
기존의 카테고리 검색 페이지에서는 카테고리를 클릭해도 URL이 같아 사용자가 어떤 카테고리에서 검색을 진행하는지 알기 어려운 문제가 있었습니다. 이를 해결하기 위해 카테고리별 URL을 세부적으로 분류하기로 결정했습니다.

또한 뒤로 가기 로직을 수정해, 사용자가 어떤 카테고리에서 검색을 진행하더라도 뒤로 가기 버튼을 클릭해서 검색 메인 페이지로 이동할 수 있도록 버튼의 로직을 수정할 예정입니다.

## To-do
- [x] 카테고리별 URL 세분화
- [x] 사용자의 검색어 URL에 포함
- [x] 뒤로가기 버튼 클릭 로직 수정

## 기타 사항
- 없음

<br>
